name: CI

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    
    - name: Build Test files
      run: |
        make test
        ./build/test
      working-directory: ./
